/donkey_car/donkey_car:
  ros__parameters:
    createcar: 'CreateCar'
    findcar: "FindCar"
    calibrate: "CalibrateCar"
    tubclean: "TubManager"
    tubplo: "ShowPredictionPlots"
    tubhist: "ShowHistogram"
    makemovie: "MakeMovieShell"
    createjs: "CreateJoystick"
    cnnactivations: "ShowCnnActivations"
    update: "UpdateCar"
    train: "Train"
    models: "ModelDatabase"
    ui: "Gui"
    foo: 123
