/**:
  ros__parameters:
    tub: 'tub_path'
    model: 'model_path'
    type: 'resnet18'
    config: './config'
    myconfig: './myconfig'
    framework: 'pytorch'
    checkpoint: '1'
    transfer: 't'
    comment: 'c'